// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Header → Links*
 */
export interface HeaderDocumentDataLinksItem {
  /**
   * Link field in *Header → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link text
   * - **API ID Path**: header.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Links field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<HeaderDocumentDataLinksItem>>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomepageDocumentDataSlicesSlice = never;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * `slices` field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice = DriversHeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = HeaderDocument | HomepageDocument | PageDocument;

/**
 * Item in *DriversHero → Default → Primary → Driver Info*
 */
export interface DriversHeroSliceDefaultPrimaryDriverInfoItem {
  /**
   * Image field in *DriversHero → Default → Primary → Driver Info*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: drivers_hero.default.primary.driver_info[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *DriversHero → Default → Primary → Driver Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: drivers_hero.default.primary.driver_info[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Surname field in *DriversHero → Default → Primary → Driver Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: drivers_hero.default.primary.driver_info[].surname
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  surname: prismic.KeyTextField;

  /**
   * Nationality field in *DriversHero → Default → Primary → Driver Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: drivers_hero.default.primary.driver_info[].nationality
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nationality: prismic.KeyTextField;

  /**
   * Highlight Image 1 field in *DriversHero → Default → Primary → Driver Info*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: drivers_hero.default.primary.driver_info[].highlight_image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  highlight_image_1: prismic.ImageField<never>;

  /**
   * Highlight Image 2 field in *DriversHero → Default → Primary → Driver Info*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: drivers_hero.default.primary.driver_info[].highlight_image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  highlight_image_2: prismic.ImageField<never>;

  /**
   * Highlight Image 3 field in *DriversHero → Default → Primary → Driver Info*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: drivers_hero.default.primary.driver_info[].highlight_image_3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  highlight_image_3: prismic.ImageField<never>;
}

/**
 * Primary content in *DriversHero → Default → Primary*
 */
export interface DriversHeroSliceDefaultPrimary {
  /**
   * Driver Info field in *DriversHero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: drivers_hero.default.primary.driver_info[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  driver_info: prismic.GroupField<
    Simplify<DriversHeroSliceDefaultPrimaryDriverInfoItem>
  >;
}

/**
 * Default variation for DriversHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DriversHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DriversHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DriversHero*
 */
type DriversHeroSliceVariation = DriversHeroSliceDefault;

/**
 * DriversHero Shared Slice
 *
 * - **API ID**: `drivers_hero`
 * - **Description**: DriversHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DriversHeroSlice = prismic.SharedSlice<
  "drivers_hero",
  DriversHeroSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataLinksItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      DriversHeroSlice,
      DriversHeroSliceDefaultPrimaryDriverInfoItem,
      DriversHeroSliceDefaultPrimary,
      DriversHeroSliceVariation,
      DriversHeroSliceDefault,
    };
  }
}
